source 'https://rubygems.org'

gem 'rails', ENV.fetch('RAILS_VERSION', '~> 8.1.0'), require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

platforms :jruby do
  gem 'jruby-openssl'
end

platforms :ruby do
  gem 'mysql2' if ENV['DB'] == 'mysql' || ENV['CI']
  gem 'pg' if ENV['DB'] == 'postgres' || ENV['CI']
  gem 'sqlite3', '>= 2.0'
end

spree_opts = { github: 'spree/spree', branch: 'main' }
gem 'spree', spree_opts
gem 'spree_admin', spree_opts

gem 'devise'
gem 'propshaft'

group :test do
  gem 'parallel_tests'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'multi_json'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-rails'
  gem 'rspec-retry'
  gem 'rspec_junit_formatter'
  gem 'simplecov'
  gem 'webmock'
  gem 'timecop'
  gem 'test-prof'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers', '~> 6.0'
end

group :test, :development do
  gem 'awesome_print'
  gem 'i18n-tasks'
  gem 'pry-byebug'
  gem 'puma'
  gem 'ffaker'
  gem 'observer'
end

gemspec
